import requests
import re

VT_API_KEY = "REDACTED"
rule_id = """$exec.rule.id""".strip()
agent_name = """$exec.agent.name""".strip()
agent_ip = """$exec.agent.ip""".strip()
manager = """$exec.manager.name""".strip()
rule_desc = """$exec.rule.description""".strip()
full_log = """$exec.full_log"""

def vt_get(url):
    headers = {"x-apikey": VT_API_KEY}
    r = requests.get(url, headers=headers, timeout=20)
    try:
        return r.status_code, r.json()
    except:
        return r.status_code, {}

if rule_id in ["550", "553"]:

    sha256 = """$exec.syscheck.sha256_after""".strip()
    file_path = """$exec.syscheck.path""".strip()
    event = """$exec.syscheck.event""".strip()

    if not sha256:
        msg = "⚠️ FIM alert received, but SHA256 hash is empty."

    else:
        status, vt = vt_get(f"https://www.virustotal.com/api/v3/files/{sha256}")

        if status == 200:
            attrs = vt.get("data", {}).get("attributes", {})
            stats = attrs.get("last_analysis_stats", {})

            malicious = int(stats.get("malicious", 0))
            suspicious = int(stats.get("suspicious", 0))
            harmless = int(stats.get("harmless", 0))
            undetected = int(stats.get("undetected", 0))

            if malicious > 0:
                severity = "🚨🚨 FIM HIGH SEVERITY ALERT 🚨🚨"
                title = "📂 Threat Intelligence Match Detected"
                action = "🔥 Action: Investigate Immediately"
            elif suspicious > 0:
                severity = "🟠🟠 FIM MEDIUM SEVERITY ALERT 🟠🟠"
                title = "📂 Suspicious File Detected"
                action = "📝 Action: Manual Review Required"
            else:
                severity = "🟡🟡 FIM LOW SEVERITY ALERT 🟡🟡"
                title = "📂 File Found In VirusTotal"
                action = "📝 Action: Review If Unexpected"

            msg = f"""{severity}

{title}
{action}

━━━━━━━━━━━━━━━━━━━━━━━
🔹 Agent Information
━━━━━━━━━━━━━━━━━━━━━━━
Agent: {agent_name}
Agent IP: {agent_ip}
Manager: {manager}

━━━━━━━━━━━━━━━━━━━━━━━
📂 File Information
━━━━━━━━━━━━━━━━━━━━━━━
File:
{file_path}

Event:
{event}

SHA256:
{sha256}

━━━━━━━━━━━━━━━━━━━━━━━
🛡 VirusTotal File Intelligence
━━━━━━━━━━━━━━━━━━━━━━━
VT Status: 200
Malicious: {malicious}
Suspicious: {suspicious}
Harmless: {harmless}
Undetected: {undetected}

File Type: {attrs.get("type_description", "N/A")}
Reputation: {attrs.get("reputation", "N/A")}

━━━━━━━━━━━━━━━━━━━━━━━
🔗 Threat Intelligence
━━━━━━━━━━━━━━━━━━━━━━━
https://www.virustotal.com/gui/file/{sha256}

━━━━━━━━━━━━━━━━━━━━━━━
📌 Recommended Actions
━━━━━━━━━━━━━━━━━━━━━━━
• Validate whether the file is authorized
• Check file source and user activity
• Isolate endpoint if malicious
• Escalate to SOC L2 / IR if required
"""

        elif status == 404:
            msg = f"""🟠🟠 FIM MEDIUM SEVERITY ALERT 🟠🟠

📂 Suspicious File Activity Detected
📝 Action Required: Manual Investigation

━━━━━━━━━━━━━━━━━━━━━━━
🔹 Alert Summary
━━━━━━━━━━━━━━━━━━━━━━━
Alert Type: File Integrity Monitoring
Severity: Medium

Reason:
File hash was not found in VirusTotal's database.

━━━━━━━━━━━━━━━━━━━━━━━
🖥 Endpoint Information
━━━━━━━━━━━━━━━━━━━━━━━
Agent: {agent_name}
Agent IP: {agent_ip}
Manager: {manager}

━━━━━━━━━━━━━━━━━━━━━━━
📂 File Information
━━━━━━━━━━━━━━━━━━━━━━━
File:
{file_path}

Event:
{event}

SHA256:
{sha256}

━━━━━━━━━━━━━━━━━━━━━━━
🛡 Threat Intelligence
━━━━━━━━━━━━━━━━━━━━━━━
VirusTotal Status:
Hash Not Found (404)

Assessment:
• File is not currently known by VirusTotal
• Could be a legitimate internal file
• Could be a newly created or previously unseen file
• Requires analyst validation

━━━━━━━━━━━━━━━━━━━━━━━
📌 Recommended Response
━━━━━━━━━━━━━━━━━━━━━━━
• Verify whether the file modification was authorized
• Review user and process activity associated with the file
• Upload the file manually to VirusTotal
• Analyze the file in a sandbox environment
• Escalate if suspicious indicators are identified

━━━━━━━━━━━━━━━━━━━━━━━
🤖 Automated Response
━━━━━━━━━━━━━━━━━━━━━━━
Generated by:
Wazuh → Shuffle → VirusTotal → Telegram
"""

        else:
            msg = f"""⚠️ FIM VirusTotal Error

VT Status: {status}
SHA256: {sha256}
"""

elif rule_id == "5758":

    match = re.search(r"from ([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)", full_log)

    if not match:
        msg = f"""⚠️ SSH ALERT ERROR

Attacker IP could not be extracted.

Full Log:
{full_log}
"""
    else:
        attacker_ip = match.group(1)
        status, vt = vt_get(f"https://www.virustotal.com/api/v3/ip_addresses/{attacker_ip}")

        if status == 200:
            attrs = vt.get("data", {}).get("attributes", {})
            stats = attrs.get("last_analysis_stats", {})

            msg = f"""🚨🚨 SSH BRUTE FORCE ALERT 🚨🚨

🔐 Multiple Failed Authentication Attempts Detected
🔥 Action Required: Investigate Source IP

━━━━━━━━━━━━━━━━━━━━━━━
🔹 Alert Summary
━━━━━━━━━━━━━━━━━━━━━━━
Alert Type: SSH Brute Force Attack
Rule ID: {rule_id}
Rule: {rule_desc}
MITRE ATT&CK: T1110 - Brute Force
Severity: High

━━━━━━━━━━━━━━━━━━━━━━━
🎯 Target Information
━━━━━━━━━━━━━━━━━━━━━━━
Hostname: {agent_name}
Target IP: {agent_ip}
Manager: {manager}

━━━━━━━━━━━━━━━━━━━━━━━
🌐 Attacker Information
━━━━━━━━━━━━━━━━━━━━━━━
Attacker IP:
{attacker_ip}

Country: {attrs.get("country", "N/A")}
ASN: {attrs.get("asn", "N/A")}
Network: {attrs.get("network", "N/A")}
Reputation: {attrs.get("reputation", "N/A")}

━━━━━━━━━━━━━━━━━━━━━━━
🛡 VirusTotal IP Intelligence
━━━━━━━━━━━━━━━━━━━━━━━
Malicious: {stats.get("malicious", 0)}
Suspicious: {stats.get("suspicious", 0)}
Harmless: {stats.get("harmless", 0)}
Undetected: {stats.get("undetected", 0)}

━━━━━━━━━━━━━━━━━━━━━━━
🔗 Threat Intelligence
━━━━━━━━━━━━━━━━━━━━━━━
https://www.virustotal.com/gui/ip-address/{attacker_ip}

━━━━━━━━━━━━━━━━━━━━━━━
📌 Recommended Response
━━━━━━━━━━━━━━━━━━━━━━━
• Review SSH authentication logs
• Verify whether the source IP is authorized
• Block or restrict the source IP if unauthorized
• Check for successful logins from same source
• Escalate to SOC L2 if activity persists
"""

        else:
            msg = f"""🟠🟠 SSH MEDIUM SEVERITY ALERT 🟠🟠

SSH Brute Force Detected

Attacker IP:
{attacker_ip}

VT Status:
{status}

VT Link:
https://www.virustotal.com/gui/ip-address/{attacker_ip}
"""

else:
    msg = f"""⚪⚪ UNHANDLED WAZUH ALERT ⚪⚪

Rule ID: {rule_id}
Rule: {rule_desc}

Agent: {agent_name}
IP: {agent_ip}
"""

print(msg)
